# Generated by Django 6.0.3 on 2026-03-15 21:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_remove_flashcard_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
